exclude_patterns:
- ".idea/"
- ".vscode/"
- "**/*.png"
- "**/*.jpg"
- "**/*.gif"
- "contratos/"
- "data/"
- "entradas2/jpgraph/"
- "entradas2/css/custom-theme/"
- "entradas2/js/"
- "iconos/"
- "imagenes/"
- "inc/ezpdf"
- "js/"
- "node_modules/"
- "phpdocker/"
- "rapido/fondos/"
- "rapido/js/prototype.js"
- "rapido/js/rico.js"
- "servicont/imagenes"