###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    webserver:
      build:
        context: .
        dockerfile: phpdocker/php/Dockerfile
      container_name: cni-webserver
      working_dir: /var/www/
      volumes:
          - .:/var/www/
      ports:
       - "8083:80"
      environment:
       - REMOTE_XDEBUG_HOST=172.18.0.1
       - MYSQL_HOSTNAME=cni-mysql
      links:
        - mysql
    mysql:
      build:
        context: .
        dockerfile: phpdocker/mysql/Dockerfile
      container_name: cni-mysql
      ports:
        - "3307:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=cni
        - MYSQL_DATABASE=centro
        - MYSQL_USER=cni
        - MYSQL_PASSWORD=inc
