###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      build:
        context: .
        dockerfile: phpdocker/mysql/Dockerfile
      container_name: cni-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=cni
        - MYSQL_DATABASE=centro
        - MYSQL_USER=cni
        - MYSQL_PASSWORD=inc
      ports:
        - "3306:3306"
    webserver:
      build:
        context: .
        dockerfile: phpdocker/php/Dockerfile
      container_name: cni-webserver
      working_dir: /var/www/html/
      volumes:
          - .:/var/www/html/
      ports:
       - "80:80"
      links:
       - mysql
